---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: true

  include:
    # runs tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - yarn test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:
        - yarn install --no-lockfile --non-interactive
        - bower install
      script:
        - yarn test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-1.13-with-ember-legacy-views
    - env: EMBER_TRY_SCENARIO=ember-1.13-without-ember-legacy-views
    - env: EMBER_TRY_SCENARIO=ember-2.4-with-ember-legacy-views
    - env: EMBER_TRY_SCENARIO=ember-2.4-without-ember-legacy-views

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --non-interactive
  - bower install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
